// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web; // Use web config for Windows
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAG4C5XG1fXPQevAUW-NmcoZTlcIv2srFY",
    authDomain: "real-estate-d048f.firebaseapp.com",
    projectId: "real-estate-d048f",
    storageBucket: "real-estate-d048f.firebasestorage.app",
    messagingSenderId: "929916563236",
    appId: "1:929916563236:web:05e752324d56132a2e4db1",
    measurementId: "G-KKLZ8EQ0Q2",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAG4C5XG1fXPQevAUW-NmcoZTlcIv2srFY",
    appId: "1:929916563236:web:05e752324d56132a2e4db1",
    messagingSenderId: "929916563236",
    projectId: "real-estate-d048f",
    storageBucket: "real-estate-d048f.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAG4C5XG1fXPQevAUW-NmcoZTlcIv2srFY",
    appId: "1:929916563236:web:05e752324d56132a2e4db1",
    messagingSenderId: "929916563236",
    projectId: "real-estate-d048f",
    storageBucket: "real-estate-d048f.firebasestorage.app",
    iosClientId: "929916563236-app.googleusercontent.com",
    iosBundleId: "com.example.realEstateApp",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAG4C5XG1fXPQevAUW-NmcoZTlcIv2srFY",
    appId: "1:929916563236:web:05e752324d56132a2e4db1",
    messagingSenderId: "929916563236",
    projectId: "real-estate-d048f",
    storageBucket: "real-estate-d048f.firebasestorage.app",
    iosClientId: "929916563236-app.googleusercontent.com",
    iosBundleId: "com.example.realEstateApp",
  );
}
